#! /bin/bash

# looks like good params:
#aws-bins/atomic-tcr /DATA/aws-data/g_5ch_rep0_24.ser tcr_out.ser 1.0 0.0001 0.0000002 0.1 1000 1 0 1 

aws-bins/atomic-tcr /DATA/aws-data/g_5ch_rep0_24.ser gpu_out.ser 1.0 0.0001 0.0000002 0.1 10 1 1 1 
#aws-bins/atomic-tcr /DATA/aws-data/g_5ch_rep0_24.ser cpu_out.ser 1.0 0.0001 0.0000002 0.1 10 0 0 12 
